name: Release Beta Version to NPM ğŸ“¦

on:
  pull_request:
    types:
      - closed

jobs:
  publish-npm:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3
      - name: Set Node version ğŸ”‚
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Install node modules ğŸ“¦
        run: yarn install --frozen-lockfile
      - name: Build for npm ğŸ—ï¸
        run: yarn build
      - name: Publish to npm registry ğŸ“¦
        run: cd dist && yarn publish --access public --tag beta
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
